### ISSUE TITLE
Chamada de diretório absoluto, não funciona projeto em outros computadores

### ISSUE THREAD

**Issue by heitor57** [heitor57/One-Week#5]
Na linha 30 do script NPC tem alguma chamada de diretório absoluto. A prova disso é que o debugger do Unity retorna o diretório absoluto do computador do Moysés, o que fara o projeto ser apenas utilizável em seu computador.

**Comment by heitor57** [comment]
A nova atualização tem o script do npc parar so que nao pude testar por causa desse bug.

**Comment by Reymax** [comment]
Bug velho que todos sabem que existe mas não como arruma

**Comment by heitor57** [comment]
Arrumado pelo Juan.
